#ifndef GENERAL_ERRORS_H
#define GENERAL_ERRORS_H

enum ConnectionError {
  CONNECTION_FAILED,
  CONNECTION_LOST,
  CONNECTION_REFUSED,
  NOT_CONNECTED,
  ALREADY_CONNECTED,
  CONNECTION_TIMEOUT,
  HANDSHAKE_TIMEOUT,
};
enum SendError {
  SEND_FAILED,
  TX_BUFFER_FULL,
  TX_BUSY,
  TX_OVERFLOW,
  TRANSMISSION_ABORTED,
  SEND_TIMEOUT,
};
enum ReceiveError {
  RECEIVED_FAILED,
  RX_BUFFER_OVERFLOW,
  RX_BUFFER_EMPTY,
  PARTIAL_RECEIVE,
  CHECKSUM_ERROR,
  CRC_ERROR,
  CORRUPTED_PACKET,
  INVALID_PACKET,
  UNEXPECTED_PACKET,
  INVALID_HEADER,
  UNSUPPORTED_MESSAGE,
  RECEIVE_TIMEOUT,
};
enum ConfigurationError {
  INVALID_ADDRESS,
  INVALID_CHANNEL,
};

enum StateError {
  INVALID_STATE,
  OPERATION_NOT_ALLOWED,
  ALREADY_IN_PROGESS,
  NOT_INITIALIZED
};

enum AvailabilityError {
  RESOURCE_UNAVAILABLE,
  PERMISSION_DENIED,
  ALREADY_OPEN,
  NOT_OPEN,
  DEVICE_NOT_FOUND,
  DEVICE_BUSY,
  UNSUPPORTED_OPERATION
};

enum OpenError {
  OPEN_FAILED,
  OPEN_TIMEOUT,
  INIT_FAILED,
};

enum ReadError {
  READ_FAILED,
  READ_TIMEOUT,
  END_OF_FILE,
  PARTIAL_READ,
};
enum WriteError {
  WRITE_FAILED,
  WRITE_TIMEOUT,
  PARTIAL_WRITE,
};

enum IntegrityError {
  INVALID_DATA,
  FORMAT_ERROR,
  DATA_CORRUPTED,
};

enum CapacityError {
  BUFFER_OVERFLOW,
  BUFFER_UNDERFLOW,
  OUT_OF_MEMORY,
  INSUFFICIENT_SPACE,
  OUTSIDE_RANGE,
};
enum TimeoutError {
  TIMEOUT,
  OPERATION_TIMEOUT,
};

enum HardwareError {
  HARDWARE_FAILURE,
  BUS_ERROR,
  DRIVER_ERROR,
};

#endif
